// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_vEcD0SfjOzosc_0icpWzs7hibiR_bs',
    appId: '1:349911351256:web:8205f95d9486dfd4e3bcad',
    messagingSenderId: '349911351256',
    projectId: 'alhelal-prime',
    authDomain: 'alhelal-prime.firebaseapp.com',
    storageBucket: 'alhelal-prime.firebasestorage.app',
    measurementId: 'G-PS9KNCBGHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-Ga8pEc30_gbO9A398F9cXIkj3dnVRY',
    appId: '1:349911351256:android:45e1f66f023fe142e3bcad',
    messagingSenderId: '349911351256',
    projectId: 'alhelal-prime',
    storageBucket: 'alhelal-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6EvgdzyITFbYJELWhd7LfQsI9kqWg4U',
    appId: '1:349911351256:ios:fc8c9f54a337b00de3bcad',
    messagingSenderId: '349911351256',
    projectId: 'alhelal-prime',
    storageBucket: 'alhelal-prime.firebasestorage.app',
    iosBundleId: 'com.example.firstStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6EvgdzyITFbYJELWhd7LfQsI9kqWg4U',
    appId: '1:349911351256:ios:fc8c9f54a337b00de3bcad',
    messagingSenderId: '349911351256',
    projectId: 'alhelal-prime',
    storageBucket: 'alhelal-prime.firebasestorage.app',
    iosBundleId: 'com.example.firstStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg_vEcD0SfjOzosc_0icpWzs7hibiR_bs',
    appId: '1:349911351256:web:66768799bd82f1d2e3bcad',
    messagingSenderId: '349911351256',
    projectId: 'alhelal-prime',
    authDomain: 'alhelal-prime.firebaseapp.com',
    storageBucket: 'alhelal-prime.firebasestorage.app',
    measurementId: 'G-LMF2V27L5H',
  );
}
